### ISSUE TITLE
Endpoint to expose most recent hotshot contract address

### ISSUE THREAD

**Issue by nomaxg** [EspressoSystems/hotshot-query-service#232]
For deployment purposes, it would be very convenient to have an API route that returns the current hotshot contract address. 

One simple approach is a simple set/get API:
`hotshot_contract/set`
`hotshot_contract/get`

The API should accept/return the hex encoded string that represents the hotshot contract `0xED15E1FE0789c524398137a066ceb2EF9884E5D8`

An even better way would be to somehow query the L1 for the most recent contract address, but I am not sure if this is feasible (something to look into).

**Comment by ImJeremyHe** [comment]
I think we can add a file `api/deployment.toml`.
```toml
[meta]
NAME = "hotshot-deployment"
DESCRIPTION = "Deployment information"
FORMAT_VERSION = "0.1.0"

[route.get_hotshot_contract]
PATH = ["hotshot_contract/get"]
DOC = "Get the address of the HotShot contract in the L1"

[route.set_hotshot_contract]
PATH = ["hotshot_contract/set"]
METHOD = "POST"
DOC = "Set the address of the HotShot contract in the L1"
```

Maybe we can use more restful APIs like
`GET /hotshot_contract`
and
`POST /hotshot_contract`
but I am not sure if `tide disco` can do this.
